spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    password:
      regex-pattern: "^(?=.*\\d)(?=.*[a-z])(?=.*[!@#$%^&*])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,}$"
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 3600000
      refresh-token:
        expiration: 604800000
    oauth2:
     google:
       client-id: 179228844613-eea7rq7f6psii5h799co0v5rlbgokpvq.apps.googleusercontent.com
       userInfoEndPoint: https://www.googleapis.com/oauth2/v3/userinfo
  error:
    include-binding-errors: always
    include-message: always


logging:
  level:
    root: DEBUG
  pattern:
    console: "{\"timestamp\":\"%d{yyyy-MM-dd HH:mm:ss.SSS}\",\"level\":\"%level\",\"thread\":\"%t\",\"logger\":\"%logger{36}\",\"message\":\"%msg\"}%n"
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-access-key:  ${AWS_SECRET_ACCESS_KEY}
    region:
      static: eu-north-1
    stack: false
    s3:
      bucket: ${AWS_BUCKET_NAME}