spring:
  datasource:
    url: jdbc:postgresql://mydatabase-instance.cc5nuqyketbc.eu-north-1.rds.amazonaws.com/thriftydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    password:
      regex-pattern: "^(?=.*\\d)(?=.*[a-z])(?=.*[!@#$%^&*])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,}$"
    jwt:
      secret-key: 78214125432A462D4A614E645267556B58703273357638792F423F4528472B4B
      expiration: 3600000
      refresh-token:
        expiration: 604800000
    oauth2:
     google:
       userInfoEndPoint: https://www.googleapis.com/oauth2/v3/userinfo
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always


#logging:
#  level:
#    root: DEBUG
#  pattern:
#    console: "{\"timestamp\":\"%d{yyyy-MM-dd HH:mm:ss.SSS}\",\"level\":\"%level\",\"thread\":\"%t\",\"logger\":\"%logger{36}\",\"message\":\"%msg\"}%n"
cloud:
  aws:
    credentials:
      access-key: AKIAQODPVBA42BHGZNHG
      secret-access-key: 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
    region:
      static: eu-north-1
    stack: false
    s3:
      bucket: thriftly-bucket